# Generated by Django 3.2.5 on 2021-08-24 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('allowed', models.BooleanField(default=True)),
                ('avatar', models.URLField(default='https://i.pinimg.com/originals/13/f4/09/13f4093020fc96ba87eae8221d071af7.jpg')),
            ],
        ),
    ]
